# Generated by Django 5.1.3 on 2024-11-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_user_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duree', models.IntegerField()),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_approvee', models.DateTimeField(blank=True, null=True)),
                ('montant_total_remboursement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='api.user')),
            ],
        ),
    ]
