# Generated by Django 5.1.3 on 2024-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='statut',
            field=models.CharField(choices=[('encours', 'En cours'), ('approuvé', 'Approuvé'), ('refusé', 'Refusé'), ('remboursé', 'Remboursé')], default='encours', max_length=10),
        ),
    ]
