# Generated by Django 5.1.3 on 2024-12-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('married', models.BooleanField()),
                ('dependents', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('self_employed', models.BooleanField()),
                ('applicant_income', models.FloatField()),
                ('coapplicant_income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('loan_amount_term', models.IntegerField()),
                ('credit_history', models.BooleanField()),
                ('property_area', models.CharField(max_length=50)),
                ('loan_status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
